### Site settings
#title: Empyrean   				  	#你博客的标题
#SEOTitle: Empyrean 	 #显示在浏览器上搜索的时候显示的标题
#header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
#email: YangLuom@gmail.com	
#description: "Empyrean"  			 #网站介绍
#keyword: "Empyrean, Empyrean Blog, Young的博客, Yang Lu, 杨璐" #关键词
#url: "https://yangluom.github.io"          # 这个就是填写你的博客地址
#baseurl: ""      # 这个我们不用填写

# 头部菜单，title: link
menu:
  Whoami: /whoami
  Github: https://github.com/yangluom
  Twitter: https://twitter.com/yangluom

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
